src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 * @Orm\Table(name="`movie`")
 * @Vich\Uploadable()
 */


class Movie
{
    /**
     * @var int
     * @ORM\Id()
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Casting;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Realisateur;

    /**
     * @ORM\Column(type="integer")
     */
    private $Annee;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="movie_image", fileNameProperty="filename")
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $Synopsis;









    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $Id): self
    {
        $this->Id = $Id;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getCasting(): ?string
    {
        return $this->Casting;
    }

    public function setCasting(string $Casting): self
    {
        $this->Casting = $Casting;

        return $this;
    }

    public function getRealisateur(): ?string
    {
        return $this->Realisateur;
    }

    public function setRealisateur(string $Realisateur): self
    {
        $this->Realisateur = $Realisateur;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->Annee;
    }

    public function setAnnee(int $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }


    public function getImage(): ?File
    {
        return $this->Image;
    }

    public function setImage(?File $Image): Movie
    {
        $this->Image = $Image;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->Synopsis;
    }

    public function setSynopsis(?string $Synopsis): self
    {
        $this->Synopsis = $Synopsis;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

}

src/Form/Movie/MovieType.php
<?php

namespace App\Form\Movie;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Titre', TextType::class, [
                'label' => 'Titre*',
                'attr' => [
                    'placeholder' => "Les Affranchis",
                ]
            ])
            ->add('Synopsis', TextareaType::class, [
                'required' => false,
                'attr' => [
                    'placeholder' => 'Dans les années 1950, à Brooklyn, le jeune Henry Hill a l\'occasion de réaliser son rêve : devenir gangster lorsqu\'un caïd local l\'intègre à son équipe. C\'est alors qu\'il rencontre James et Tommy, 2 truands d\'une rare brutalité. Lorsqu\'il séduit la ravissante Karen, le jeune mafieux s\'imagine que plus rien ni personne ne pourra jamais lui résister.',
                    'maxlength' => 500
                ]
            ])
            ->add('Casting', TextType::class, [
                'required' => false,
                'attr' => [
                    'placeholder' => "Robert De Niro, Joe Pesci",
                ]
            ])
            ->add('Realisateur', TextType::class, [
                'label' => 'Réalisateur*',
                'attr' => [
                    'placeholder' => "Martin Scorsese",
                ]
            ])
            ->add('Annee', IntegerType::class, [
                'label' => 'Année*',
                'attr' => [
                    'placeholder' => "1990",
                    'min' => 0,
                    'max' => 2020,
                ]
            ])
            ->add('Image', FileType::class, [
                'label' => 'Image',
                'required' => false,
            ])
        ;
    }
}
?>

src/Form/Movie/SearchForm.php
<?php

namespace App\Form\Movie;

use App\Data\SearchData;
use App\Entity\Movie;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;

class SearchForm extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('q', TextType::class, [
                'label' => false,
                'required' => false,
                'attr' => [
                    'class' => 'p-2 w-100',
                    'placeholder' => 'Mots-clés',
                ]
            ])
            ->add('minDate', IntegerType::class, [
                'label' => "Sortis après",
                'required' => false,
                'attr' => [
                    'min' => 0,
                    'max' => 2020,
                    'style' => 'width: 50%',
                    'class' => 'mx-3 py-1',
                    'placeholder' => 'Date minimale'
                ]
            ])
            ->add('maxDate', IntegerType::class, [

                'label' => "Sortis avant",
                'required' => false,
                'attr' => [
                    'min' => 0,
                    'max' => 2020,
                    'style' => 'width: 50%',
                    'class' => 'mx-3 py-1',
                    'placeholder' => 'Date maximale'
                ]
            ])
            ->add('orderBy', ChoiceType::class, [
                'placeholder' => false,
                'label' => 'Trier ',
                'required' => false,
                'attr' => [
                    'class' => 'mx-3 py-1',
                ],
                'choices' => [
                    'Du + au - récent' => 0,
                    'Du - au + récent' => 1,
                    'Par ordre alphabétique' => 2,
                    'Par odre désalphabétique' => 3
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SearchData::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }
}

?>

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;


use Knp\Component\Pager\PaginatorInterface;

use App\Entity\Movie;

use App\Data\SearchData;

use App\Form\Movie\SearchForm;
use App\Form\Movie\MovieType;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;

class MovieController extends AbstractController
{
    
    /**
     * @Route("/movie/", name="home")
     */
    public function home()
    {
        return $this->render('movie/home.html.twig');
    }

    /**
     * @Route("/movie/search", name="search")
     */
    public function search(PaginatorInterface $paginator, Request $request){
        
        $data = new SearchData();
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);

        $result = $this->getDoctrine()->getRepository(Movie::class)->findSearch($data);

        $movies = $paginator->paginate(
            $result,
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('movie/search.html.twig', [
            'liste' => $movies,
            'nbMovies' => count($result),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/movie/add", name="add_movie")
     */
    public function addMovie(Request $request)
    {
        $movie = new Movie();

        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $movie = $form->getData();
            
            dump($movie);
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($movie);
            $manager->flush();

            return $this->render('movie/success.html.twig', array(
                'movie' => $movie
            ));
        }

        return $this->render('movie/add.html.twig', [
            'formMovie' => $form->createView()
        ]);
    }

    /**
     * @Route("/movie/success", name="movie_success")
     */
    public function addSuccess($movie){
        return $this->render('movie/success.html.twig', [
            'newMovie' => $movie
        ]);
    }

    /**
     * @Route("/movie/{id}", name="movie_show")
     * @param $id integer
     * @return Response
     */
    public function getMovieById($id)
    {
        $movie = $this->getDoctrine()
            ->getRepository(Movie::class)
            ->find($id);
        
        if (!$movie){
            throw $this->createNotFoundException('No movie found for id '.$id);
        }

        return $this->render('movie/movieById.html.twig', [
            'movie' => $movie,
        ]);
    }

    

}

?>

templates/movie/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un film{% endblock %}

{% block body %}
    <div class="container h-100">
        <div class="d-flex justify-content-center my-5">
            <h1>Ajoutez votre film</h1>
        </div>

        {{ form_start(formMovie) }}

        <div class="d-flex justify-content-center mb-4">
            {# Affiche les labels #}
            <div class="d-flex flex-column">
                <div class="form-control-lg">
                    {{ form_label(formMovie.Titre) }}
                </div>
                <div class="form-control-lg">
                    {{ form_label(formMovie.Synopsis) }}
                    <p id="compteur"></p>
                </div>
                <div class="form-control-lg">
                    {{ form_label(formMovie.Realisateur) }}
                </div>
                <div class="form-control-lg">
                    {{ form_label(formMovie.Casting) }}
                </div>
                <div class="form-control-lg">
                    {{ form_label(formMovie.Annee) }}
                </div>
                <div class="form-control-lg">
                    {{ form_label(formMovie.Image) }}
                </div>
            </div>
            {# ################################### #}
            {# Affiche les widget, cad les input #}
            <div class="d-flex flex-column">
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Titre) }}
                </div>
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Synopsis, {'id': 'zoneTexte'}) }}
                </div>
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Realisateur) }}
                </div>
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Casting) }}
                </div>
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Annee) }}
                </div>
                <div class="form-control-lg">
                    {{ form_widget(formMovie.Image) }}
                </div>
            </div>
            {# ###################################### #}
        </div>
        <div class="row justify-content-center">
            <button class="btn btn-primary">Ajouter</button>
        </div>
        {{ form_end(formMovie) }}
    </div>
{% block javascripts %}
    <script>
        var zoneTexte = document.getElementById('zoneTexte');
        zoneTexte.addEventListener('keydown', function() {
            var compteur = document.getElementById('compteur');
            compteur.innerHTML = zoneTexte.value.length + "/500";
        });
    </script>

{% endblock %}
{% endblock %} 

templates/movie/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <div class="container">

        <div class="d-flex justify-content-center my-5">
            <h1>Bienvenue sur le projet Movie !</h1>
        </div>

        <div class="description">
            <h3>Intitulé</h3>
            <p>La plateforme Movie sur laquelle vous vous trouvez actuellement réfère plus de 50 films notables et intergénérationnel. Vous pouvez retrouvez des classiques comme Métropolis de Lang ou encore Joker de Philips.
                <br><br>
                Si vous pensez qu'un film mérite sa place parmi cette liste, libre à vous de l'ajouter grâce à l'onglet "Ajouter un film".
                <br><br>
                Vous verrez qu'un film doit obligatoirement avoir certains critères comme un titre ou un réalisateur. Movie vous permet tout de même de rajouter le casting ou encore le synopsis de votre film favori.

            </p>

            <h3>Objectif</h3>
            <p>L'objectif de ce projet est principalement... la chronophagie qu'il m'apporte.
                <br><br>
                En effet, durant ce confinement, chacun s'occupe comme il peut, et moi, j'adore 2 choses:
                Les grands films et apprendre.
                J'ai donc naturellement tourné ce projet autour des films.
                <br><br>
                Pour ce qui est d'apprendre, j'ai développé ce projet avec Symfony5, une toute nouvelle technologie pour moi. J'ai pu apprendre ses bases comme le système d'Entity, de Controller et de Repository, mais aussi les bases de Twig et Doctrine.
                <br><br>
                Vous pouvez trouver mon site web <a target="_blank" href="https://mickaelurien.fr">ici</a> ou bien dans le footer en bas de page pour en savoir sur ma formation et mes projets.
            </p>

        </div>
    </div>

{% endblock %}

templates/movie/listMovies.html.twig
{% block body %}


            {% if liste is empty %}
                    <div class="container">
                        <div class="d-flex justify-content-center mt-5">
                            <h1>Pas de résultats</h1>
                        </div>
                    </div>
            {% else %}
                <div class="col-11 offset-1">
                    <div class="row">
                        {% for movie in liste %}
                            {% include 'movie/oneMovie.html.twig'%}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}



<div class="d-flex justify-content-center">
    <div>
        {{ knp_pagination_render(liste) }}
    </div>
</div>
{% endblock %}

templates/movie/movieById.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ movie.Titre }}{% endblock %}

{% block body %}
    <div class="container d-flex py-5">
        <div class="offset-1 col-4">
            {% if movie.filename %}
                <img height="200px" src="{{ asset('img/movies/') }}{{ movie.filename }}" alt="{{ movie.Titre }}">
            {% endif %}
        </div>
        <div class="col-6">
            <div class="d-flex flex-column justify-content-center mb-3">
                <h4 class="mb-3">{{ movie.Titre }}</h4>
            </div>
            <p>Réalisé par {{ movie.Realisateur }}</p>

            {% if movie.Casting %}
                <p>Avec {{ movie.Casting }}</p>
            {% endif %}

            <p>Sortie en {{ movie.Annee }}</p>


            {% if movie.Synopsis %}
                <p>Synopsis : </p>
                <p>{{ movie.Synopsis }}</p>
            {% endif %}
        </div>


    </div>

{% endblock %}

templates/movie/oneMovie.html.twig
{% block body %}
    <div class="col-5 card my-3 mx-5" style="width: 40rem;">
        <a href="{{ path('movie_show', {'id': movie.Id}) }}" style="text-decoration: none">
            <div class="row" style="flex-wrap: nowrap">
                <div class="card-body mx-5 my-3" >
                    <h5 class="card-title">{{ movie.titre }}</h5>
                    <p class="card-text">Réalisé par {{ movie.realisateur }}</p>
                    {% if movie.Casting %}
                    <p class="card-text">Avec {{ movie.casting }}</p>
                    {% endif %}
                    <p class="card-text">{{ movie.Annee }}</p>
                </div>
                {% if movie.filename %}
                    <div style="padding: 30px">
                        <img height="150px" src="{{ vich_uploader_asset(movie, 'Image') | imagine_filter('thumb') }}" alt="{{ movie.Titre }}">
                    </div>
                {% endif %}
            </div>

        </a>
    </div>




{% endblock %}

templates/movie/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherchez un film{% endblock %}

{% block body %}

    {# TITRE #}
    <div class="d-flex justify-content-center my-5">
        <h1>Recherchez un film avec vos critères !</h1>
    </div>
    {# FORMULAIRE #}
    <div class="container js-filter-form">
        {{ form_start(form) }}
        <div class="row mb-5">
            <div class="col-10">
                {{ form_row(form.q) }}
            </div>
            <div class="col-2">
                <button class="btn btn-primary py-2">Rechercher</button>
            </div>
        </div>
        <div class="row col-12 mb-5">
            <div class="col-3 px-0">
                {{ form_row(form.minDate) }}
            </div>
            <div class="col-3 px-0">
                {{ form_row(form.maxDate) }}
            </div>
            <div class="col-4">
                {{ form_row(form.orderBy) }}
            </div>
            <div class="col-2">
                <p style="margin-top: 8px">{{ nbMovies }} résultats</p>
            </div>
        </div>
        {{ form_end(form) }}
    </div>

    {# CONTENU #}
    {% if liste is empty %}
        <div class="d-flex justify-content-center mt-5">
            <h1>Pas de résultats</h1>
        </div>
    {% else %}
        <div class="col-11 offset-1">
            <div class="row">
                {% for movie in liste %}
                    {% include 'movie/oneMovie.html.twig' %}
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {# PAGINATION #}
    <div class="d-flex justify-content-center js-filter-pagination pb-5 pt-3">
        {{ knp_pagination_render(liste) }}
    </div>

{% endblock %}

templates/movie/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ movie.Titre }} à été ajouté{% endblock %}

{% block body %}
    <div class="container">
        <div class="d-flex my-5 justify-content-center">
            <h1>{{ movie.Titre }} de {{ movie.Realisateur}} à été ajouté avec succés ! </h1>
        </div>
        <div class="d-flex justify-content-center">
            <p style="font-size: 24px">Vous pouvez le retrouver dans <a style="wrap: no-wrap" href="{{ path('search') }}">la liste des films</a></p>
        </div>

    </div>
{% endblock %}